### ISSUE TITLE
tkinter not found on WSL2

### ISSUE THREAD

**Issue by namtrah** [Mara-Li/Obsidian-Snippet-Manager#3]
**Describe the bug**
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uusiwv99/ttkthemes/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uusiwv99/ttkthemes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-uusiwv99/ttkthemes/pip-egg-info
         cwd: /tmp/pip-install-uusiwv99/ttkthemes/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uusiwv99/ttkthemes/setup.py", line 7, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**To Reproduce**
1. On Microsoft Windows Subsystem for Linux (Ubuntu 20.04 LTS)
2. sudo apt install pythong3-pip git python3
3. pip install Obsidian-Snippet-Manager --upgrade

**Log** 
I can add logs later, if you can tell me where to look

**Desktop
 - OS: Windows 11: WSL 2: Ubuntu 20.04 LTS
 - Browser: none used
 - Version ?

I presume there is a missing dependency on WSL, but not fully sure.

**Comment by Mara-Li** [comment]
You need to install tkinter, as the error code said. 
`sudo apt-get install python3-tk`

I didn't test on WSL2. 
The plugin work great on windows (I program first on windows).

**Comment by namtrah** [comment]
Sorry for the delay. Yes, adding python3-tk helped, but it still errored. I needed to also install python3-testresources. Just FYI. Now it is installed and seems to work just fine. Thank you.

```
Successfully built ttkthemes
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
```

**Comment by Mara-Li** [comment]
I will edit the readme to add these information !
